"""Stage 4 — the offline evaluator, and the boundaries it must not cross.

Three groups of tests, answering three different questions.

**Does it measure the right thing?** The evaluator carries the repository's
only non-test definition of "correct auto-resolution", so the first thing
proved here is that it is not a *second* definition: it is checked
case-for-case against the predicate already asserted by
``test_stage3_dev_diagnostic.py::test_no_dev_case_is_auto_resolved_incorrectly``.

**Does it fail when it should?** An evaluator that quietly scores a subset,
or a contaminated cohort, produces a better number than the run deserved.
Every such path is asserted to raise rather than report.

**Does it stay offline and outside the production boundary?** Structurally
(no provider module is imported anywhere in the package; nothing under
``src/finrecon`` imports the package) and at runtime
(``provider_calls_made()`` is false, and a provider that raises on contact is
never contacted).

No test here reaches a network. The corpus is generated by
``tests.stage3_fakes.MechanicalInvestigator``, the same deterministic
non-linguistic stand-in the Stage-3 diagnostics use.
"""

from __future__ import annotations

import ast
import dataclasses
import json
from pathlib import Path

import pytest

from finrecon.agent.cache import TrajectoryCache
from finrecon.ledger.store import LedgerStore
from finrecon.stage3 import run_stage3

from benchmark.eval.cohort import build_cohort, enforce
from benchmark.eval.compare import compare
from benchmark.eval.errors import (
    CohortError,
    EvaluationInputError,
    GroundTruthPolicyError,
    ReplayIntegrityError,
)
from benchmark.eval.evaluate import EvaluationConfig, evaluate
from benchmark.eval.groundtruth import GroundTruthEntry, load_ground_truth
from benchmark.eval.scoring import (
    WRONG_NO_CORRECT_ANSWER,
    WRONG_SETTLEMENT,
    soundness_violations,
    telemetry_from_payloads,
    trajectory_metrics,
    verdict_for,
)
from benchmark.eval.sources import (
    assemble,
    cohort_from_records,
    decode_text,
    load_cache_dir,
    load_run_dump,
    read_cohort_file,
)

FAKE_PROVIDER = "mechanical"
FAKE_MODEL = "mechanical-investigator-v1"

T2_SAMPLE = 12
T3_SAMPLE = 4


# --- corpus ----------------------------------------------------------------


@pytest.fixture(scope="session")
def corpus(benchmark_dir, dev_ground_truth, tmp_path_factory):
    """A real recorded trajectory corpus, produced with zero network access.

    Runs the deterministic stand-in over a small DEV slice and lets the
    trajectory cache write the fixtures, which is exactly the artifact shape
    the evaluator consumes in production use.
    """
    from finrecon.agent.providers.chain import ProviderChain
    from finrecon.pipeline import process_batch
    from tests.stage3_fakes import MechanicalInvestigator

    t2 = sorted(c for c, e in dev_ground_truth.items() if e["tier"] == "T2")[:T2_SAMPLE]
    t3 = sorted(c for c, e in dev_ground_truth.items() if e["tier"] == "T3")[:T3_SAMPLE]
    selected = tuple(sorted([*t2, *t3]))

    directory = tmp_path_factory.mktemp("stage4-corpus")
    with LedgerStore(":memory:") as store:
        batch = process_batch(store=store, benchmark_dir=benchmark_dir, split="dev")
        run_stage3(
            store=store,
            batch_result=batch,
            chain=ProviderChain((MechanicalInvestigator(),)),
            cache=TrajectoryCache(directory),
            case_ids=frozenset(selected),
        )
    return {"dir": directory, "t2": tuple(t2), "t3": tuple(t3), "all": selected}


def _config(benchmark_dir, corpus, tmp_path, **overrides):
    base = dict(
        benchmark_dir=benchmark_dir,
        split="dev",
        trajectory_dirs=(corpus["dir"],),
        provider_id=FAKE_PROVIDER,
        model=FAKE_MODEL,
    )
    base.update(overrides)
    return EvaluationConfig(**base)


@pytest.fixture(scope="session")
def t2_evaluation(benchmark_dir, corpus, tmp_path_factory):
    config = _config(
        benchmark_dir, corpus, None, cohort_ids=corpus["t2"], expected_tier="T2"
    )
    return evaluate(config, staging_dir=tmp_path_factory.mktemp("stage4-stage") / "t")


# --- correctness is not redefined -----------------------------------------


class TestCorrectnessSemanticsAreReused:
    def test_the_evaluator_predicate_matches_the_stage_three_diagnostic(
        self, dev_stage3_result, dev_ground_truth
    ):
        """The evaluator must agree with the repo's existing predicate, exactly.

        The comparison predicate below is transcribed from
        ``test_no_dev_case_is_auto_resolved_incorrectly``. If the evaluator
        ever grows its own notion of correctness, this diverges on some case
        and fails -- which is the whole point of asserting it over the full
        DEV residual rather than a sample.
        """
        result, _, _ = dev_stage3_result
        checked = 0
        for outcome in result.resolved():
            expected = dev_ground_truth[outcome.case_id]["correct_relationship"]
            if expected is None:
                reference_wrong = True
            else:
                reference_wrong = (
                    tuple(sorted(expected["settlement_ids"]))
                    != outcome.decision.resolved_settlement_ids
                )

            entry = _entry(dev_ground_truth, outcome.case_id)
            verdict = verdict_for(outcome, entry)
            assert verdict.correct is not reference_wrong, outcome.case_id
            checked += 1
        assert checked > 0

    def test_resolving_a_case_with_no_correct_answer_is_wrong(
        self, dev_stage3_result, dev_ground_truth
    ):
        result, _, _ = dev_stage3_result
        outcome = result.resolved()[0]
        entry = dataclasses.replace(
            _entry(dev_ground_truth, outcome.case_id), correct_relationship=None
        )
        verdict = verdict_for(outcome, entry)
        assert verdict.correct is False
        assert verdict.wrong_reason == WRONG_NO_CORRECT_ANSWER

    def test_resolving_to_another_settlement_is_wrong(
        self, dev_stage3_result, dev_ground_truth
    ):
        result, _, _ = dev_stage3_result
        outcome = result.resolved()[0]
        entry = _entry(dev_ground_truth, outcome.case_id)
        moved = dataclasses.replace(
            entry, correct_relationship={"settlement_ids": ["setl_dev_999999"]}
        )
        verdict = verdict_for(outcome, moved)
        assert verdict.correct is False
        assert verdict.wrong_reason == WRONG_SETTLEMENT
        assert verdict.truth_settlement_ids == ("setl_dev_999999",)
        assert verdict.predicted_candidate_id == outcome.decision.resolved_candidate_id
        assert verdict.termination_reason == outcome.trajectory.termination_reason
        assert verdict.evidence_relations, "a wrong resolution must still name its evidence"


def _entry(ground_truth: dict, case_id: str) -> GroundTruthEntry:
    raw = ground_truth[case_id]
    return GroundTruthEntry(
        case_id=case_id,
        tier=raw["tier"],
        archetype=raw["archetype"],
        required_outcome=raw["required_outcome"],
        correct_relationship=raw["correct_relationship"],
        true_reference=raw["true_reference"],
        value_at_stake_paise=raw["value_at_stake_paise"],
    )


# --- cohort ----------------------------------------------------------------


class TestCohortReconstruction:
    def test_an_exact_cohort_is_reconstructed_from_multiple_sources(
        self, benchmark_dir, corpus, tmp_path
    ):
        """The real workflow: one source is short, a second covers the gap."""
        records = load_cache_dir(corpus["dir"])
        by_case = {r.case_id: r for r in records}
        wanted = corpus["t2"]
        first = [by_case[c] for c in wanted[: len(wanted) - 3]]
        second = [by_case[c] for c in wanted[len(wanted) - 3 :]]

        assembled = assemble([first, second])
        assert set(assembled.case_ids) == set(wanted)
        assert assembled.duplicates == {}
        assert sum(assembled.per_source_counts.values()) == len(wanted)

    def test_a_case_offered_by_two_sources_is_reported_as_a_duplicate(self, corpus):
        records = load_cache_dir(corpus["dir"])
        overlap = records[:3]
        assembled = assemble([records, overlap])
        assert set(assembled.duplicates) == {r.case_id for r in overlap}
        for labels in assembled.duplicates.values():
            assert len(labels) == 2

    def test_first_source_wins_and_later_sources_only_fill_gaps(self, corpus):
        records = load_cache_dir(corpus["dir"])
        a, b = records[:2], records[1:3]
        assembled = assemble([a, b])
        assert assembled.records[records[1].case_id].source == a[1].source

    def test_a_duplicate_in_the_requested_cohort_is_rejected(
        self, benchmark_dir, corpus
    ):
        ground_truth = load_ground_truth(benchmark_dir, "dev")
        repeated = (*corpus["t2"], corpus["t2"][0])
        report = build_cohort(
            requested=repeated,
            available=corpus["all"],
            duplicate_sources={},
            ground_truth=ground_truth,
        )
        assert report.duplicate_requested == (corpus["t2"][0],)
        with pytest.raises(CohortError, match="duplicate case IDs"):
            enforce(report, require_exact=True, require_tier=False)

    def test_a_missing_case_fails_an_exact_cohort(self, benchmark_dir, corpus):
        ground_truth = load_ground_truth(benchmark_dir, "dev")
        report = build_cohort(
            requested=(*corpus["t2"], "case:bnk_dev_000999"),
            available=corpus["all"],
            duplicate_sources={},
            ground_truth=ground_truth,
        )
        assert report.missing == ("case:bnk_dev_000999",)
        assert not report.complete
        with pytest.raises(CohortError):
            enforce(report, require_exact=True, require_tier=False)

    def test_an_unscorable_case_is_always_fatal(self, benchmark_dir, corpus):
        """No ground-truth row means no score, exact cohort or not."""
        ground_truth = load_ground_truth(benchmark_dir, "dev")
        ground_truth.pop(corpus["t2"][0])
        report = build_cohort(
            requested=None,
            available=corpus["t2"],
            duplicate_sources={},
            ground_truth=ground_truth,
        )
        assert report.unknown_to_ground_truth == (corpus["t2"][0],)
        with pytest.raises(CohortError, match="no ground-truth row"):
            enforce(report, require_exact=False, require_tier=False)

    def test_extra_available_cases_are_reported_and_not_scored(
        self, benchmark_dir, corpus
    ):
        ground_truth = load_ground_truth(benchmark_dir, "dev")
        report = build_cohort(
            requested=corpus["t2"],
            available=corpus["all"],
            duplicate_sources={},
            ground_truth=ground_truth,
        )
        assert set(report.extra) == set(corpus["t3"])
        assert set(report.case_ids) == set(corpus["t2"])


class TestTierContamination:
    def test_a_clean_t2_cohort_reports_no_contamination(self, t2_evaluation):
        cohort = t2_evaluation.report["cohort"]
        assert cohort["tier_counts"] == {"T2": T2_SAMPLE}
        assert cohort["all_expected_tier"] is True
        assert cohort["contamination"] == []

    def test_a_t3_case_in_a_t2_cohort_is_detected_and_fatal(
        self, benchmark_dir, corpus
    ):
        ground_truth = load_ground_truth(benchmark_dir, "dev")
        polluted = (*corpus["t2"], corpus["t3"][0])
        report = build_cohort(
            requested=polluted,
            available=corpus["all"],
            duplicate_sources={},
            ground_truth=ground_truth,
            expected_tier="T2",
        )
        assert report.tier_counts == {"T2": T2_SAMPLE, "T3": 1}
        assert report.all_expected_tier is False
        assert [c["case_id"] for c in report.contamination] == [corpus["t3"][0]]
        with pytest.raises(CohortError, match="pinned to T2"):
            enforce(report, require_exact=True, require_tier=True)

    def test_contamination_can_be_reported_without_failing(self, benchmark_dir, corpus):
        ground_truth = load_ground_truth(benchmark_dir, "dev")
        report = build_cohort(
            requested=(*corpus["t2"], corpus["t3"][0]),
            available=corpus["all"],
            duplicate_sources={},
            ground_truth=ground_truth,
            expected_tier="T2",
        )
        enforce(report, require_exact=True, require_tier=False)
        assert report.contamination


# --- scoring ---------------------------------------------------------------


class TestScoring:
    def test_the_t2_cohort_scores_with_no_wrong_resolutions(self, t2_evaluation):
        metrics = t2_evaluation.report["metrics"]
        assert metrics["investigated"] == T2_SAMPLE
        assert metrics["wrong_auto_resolutions"] == 0
        assert metrics["auto_resolved"] == metrics["correct_auto_resolutions"]
        assert metrics["value_at_risk_paise"] == 0
        assert t2_evaluation.report["wrong_resolutions"] == []
        if metrics["auto_resolved"]:
            assert metrics["auto_resolution_accuracy"] == 1.0

    def test_every_resolution_is_correct_against_ground_truth(self, t2_evaluation):
        resolved = [v for v in t2_evaluation.verdicts if v.resolved]
        assert resolved, "the corpus must contain resolutions for this to mean anything"
        for verdict in resolved:
            assert verdict.correct is True
            assert verdict.predicted_settlement_ids == verdict.truth_settlement_ids

    def test_t3_cases_escalate_safely_and_count_as_correct_escalations(
        self, benchmark_dir, corpus, tmp_path
    ):
        config = _config(
            benchmark_dir, corpus, tmp_path, cohort_ids=corpus["t3"], expected_tier="T3"
        )
        result = evaluate(config, staging_dir=tmp_path / "stage")
        metrics = result.report["metrics"]
        assert metrics["auto_resolved"] == 0
        assert metrics["escalated"] == T3_SAMPLE
        assert metrics["wrong_auto_resolutions"] == 0
        assert metrics["truly_ambiguous_cases"] == T3_SAMPLE
        assert metrics["correctly_escalated"] == T3_SAMPLE
        assert metrics["escalation_recall"] == 1.0
        # No resolvable case in the cohort, so match rate is undefined, not zero.
        assert metrics["overall_match_rate"] is None
        assert metrics["auto_resolution_accuracy"] is None

    def test_rates_are_none_rather_than_zero_on_an_empty_denominator(
        self, t2_evaluation
    ):
        for key in ("auto_resolution_accuracy", "overall_match_rate"):
            value = t2_evaluation.report["metrics"][key]
            assert value is None or isinstance(value, float)


class TestSoundness:
    def test_a_clean_run_reports_no_soundness_violations(self, t2_evaluation):
        sound = t2_evaluation.report["soundness"]
        assert sound["total_violations"] == 0
        assert sound["violations"] == []
        assert sound["checks_available"] is True

    def test_a_fabricated_fragment_is_caught(self, t2_evaluation):
        """Doctor a real outcome so the check has something to find."""
        outcome = next(o for o in t2_evaluation.replay.stage3.resolved())
        doctored = dataclasses.replace(
            outcome,
            validator_result=outcome.validator_result.model_copy(
                update={
                    "admissible_fragments": (
                        *outcome.validator_result.admissible_fragments,
                        "NOT-IN-THE-NARRATION-XYZ",
                    )
                }
            ),
        )
        violations = soundness_violations([doctored])
        assert any(v.check == "fragment_present_in_narration" for v in violations)

    def test_an_undeclared_relation_is_caught(self, t2_evaluation):
        outcome = next(o for o in t2_evaluation.replay.stage3.resolved())
        declaration = dict(outcome.decision.policy_declaration)
        declaration["accepted_relation_ids"] = ["exact"]
        doctored = dataclasses.replace(
            outcome,
            decision=outcome.decision.model_copy(
                update={"policy_declaration": declaration}
            ),
        )
        violations = soundness_violations([doctored])
        assert any(v.check == "accepted_relation_ids_only" for v in violations)

    def test_a_broken_snapshot_integrity_flag_is_caught(self, t2_evaluation):
        outcome = t2_evaluation.replay.stage3.outcomes[0]
        doctored = dataclasses.replace(
            outcome,
            validator_result=outcome.validator_result.model_copy(
                update={"snapshot_integrity_ok": False}
            ),
        )
        violations = soundness_violations([doctored])
        assert any(v.check == "snapshot_integrity" for v in violations)


# --- agent / tool and provider aggregation ---------------------------------


class TestAggregation:
    def test_tool_validation_reasons_are_counted_and_always_present(self):
        payloads = [
            {
                "termination_reason": "tool_validation_failed",
                "tool_invocations": [
                    {"validation_error_reason": "duplicate_argument_key",
                     "status": "validation_failed", "output": None},
                    {"validation_error_reason": "unknown_candidate",
                     "status": "validation_failed", "output": None},
                    {"validation_error_reason": None, "status": "succeeded",
                     "output": {"ok": True}},
                ],
            },
            {
                "termination_reason": "deterministic_policy_resolved",
                "tool_invocations": [
                    {"validation_error_reason": "malformed_arguments_json",
                     "status": "validation_failed", "output": None},
                ],
            },
        ]
        metrics = trajectory_metrics(payloads)
        assert metrics["tool_validation_failed"] == 1
        assert metrics["deterministic_policy_resolved"] == 1
        assert metrics["tool_validation_reasons"]["duplicate_argument_key"] == 1
        assert metrics["tool_validation_reasons"]["unknown_candidate"] == 1
        assert metrics["tool_validation_reasons"]["malformed_arguments_json"] == 1
        assert metrics["tool_validation_reasons"]["unknown_tool"] == 0, (
            "a reason that never fired must be an explicit zero, not absent"
        )
        assert metrics["tool_validation_rejections_total"] == 3
        assert metrics["cases_with_any_validation_failure"] == 2

    def test_a_skipped_invocation_is_counted_separately(self):
        metrics = trajectory_metrics([
            {
                "termination_reason": "tool_validation_failed",
                "tool_invocations": [
                    {"validation_error_reason": "duplicate_argument_key",
                     "status": "validation_failed", "output": None},
                    {"validation_error_reason": None,
                     "status": "skipped_due_to_batch_rejection", "output": None},
                ],
            }
        ])
        assert metrics["tool_invocations_skipped"] == 1
        assert metrics["tool_invocations_total"] == 2

    def test_provider_failures_are_aggregated_by_class(self):
        payloads = [
            {
                "provider_chain": ["gorouter:m"],
                "total_latency_ms": 10,
                "steps": [
                    {
                        "provider": "gorouter",
                        "model": "m",
                        "reported_model": None,
                        "fallback_used": False,
                        "fallback_reason": None,
                        "attempts": [
                            {"outcome": "server_error",
                             "error_class": "ProviderInfrastructureError"},
                            {"outcome": "success", "error_class": None},
                        ],
                        "usage": {"total_tokens": 100},
                    }
                ],
            }
        ]
        tele = telemetry_from_payloads(payloads)
        assert tele["provider_failed_attempts"] == 1
        assert tele["provider_error_classes"] == {"ProviderInfrastructureError": 1}
        assert tele["provider_attempt_outcomes"] == {"server_error": 1, "success": 1}

    def test_requested_and_reported_models_are_never_conflated(self):
        payloads = [
            {
                "provider_chain": ["gorouter:claude-opus-5-thinking"],
                "steps": [
                    {
                        "provider": "gorouter",
                        "model": "claude-opus-5-thinking",
                        "reported_model": "claude-opus-5",
                        "fallback_used": False,
                        "fallback_reason": None,
                        "attempts": [{"outcome": "success", "error_class": None}],
                        "usage": {"total_tokens": 10},
                    }
                ],
            }
        ]
        tele = telemetry_from_payloads(payloads)
        assert tele["models_requested"] == {"gorouter:claude-opus-5-thinking": 1}
        assert tele["models_reported"] == {"gorouter:claude-opus-5": 1}
        assert tele["requested_matches_reported"] is False

    def test_a_provider_that_reports_no_model_is_unknown_not_mismatched(self):
        payloads = [
            {
                "steps": [
                    {
                        "provider": "openrouter",
                        "model": "stealth/ox-alpha",
                        "reported_model": None,
                        "fallback_used": False,
                        "fallback_reason": None,
                        "attempts": [{"outcome": "success", "error_class": None}],
                        "usage": {"total_tokens": 5},
                    }
                ]
            }
        ]
        tele = telemetry_from_payloads(payloads)
        assert tele["models_reported"] == {}
        assert tele["requested_matches_reported"] is None

    def test_tokens_and_steps_are_averaged_per_case(self, t2_evaluation):
        tele = t2_evaluation.report["telemetry"]
        assert tele["cases"] == T2_SAMPLE
        assert tele["model_steps_total"] >= T2_SAMPLE
        assert tele["model_steps_mean_per_case"] > 0
        assert tele["tokens_mean_per_case"] >= 0

    def test_accepted_relations_are_aggregated(self, t2_evaluation):
        relations = t2_evaluation.report["agent"]["accepted_evidence_relations"]
        declared = set(
            t2_evaluation.report["configuration"]["policy_declaration"][
                "accepted_relation_ids"
            ]
        )
        assert set(relations) <= declared
        assert sum(relations.values()) > 0


# --- offline guarantee -----------------------------------------------------


class TestOfflineGuarantee:
    PROVIDER_NAMES = (
        "openrouter",
        "gorouter",
        "groq",
        "gemini",
        "openai_compatible",
    )

    def _eval_sources(self) -> list[Path]:
        import benchmark.eval as package

        root = Path(package.__file__).resolve().parent
        return sorted(root.rglob("*.py"))

    def test_the_evaluator_package_has_files_to_check(self):
        assert len(self._eval_sources()) >= 8

    def test_no_evaluator_module_imports_a_provider(self):
        """Structural: the package cannot call a model because it never imports one."""
        for path in self._eval_sources():
            tree = ast.parse(path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                module = None
                if isinstance(node, ast.ImportFrom):
                    module = node.module or ""
                elif isinstance(node, ast.Import):
                    module = node.names[0].name
                if module and "agent.providers" in module:
                    pytest.fail(f"{path.name} imports a provider module: {module}")
                if module:
                    for name in self.PROVIDER_NAMES:
                        assert not module.endswith(f"providers.{name}"), path.name

    def test_evaluation_makes_zero_provider_calls(self, t2_evaluation):
        assert t2_evaluation.report["offline_guarantee"]["provider_calls_made"] is False
        assert t2_evaluation.replay.provider_calls_made is False
        assert t2_evaluation.replay.cache_hits == T2_SAMPLE
        assert t2_evaluation.report["configuration"]["provider_constructed"] is False
        assert t2_evaluation.report["configuration"]["offline"] is True

    def test_the_underlying_stage_three_result_reports_no_provider_calls(
        self, t2_evaluation
    ):
        assert t2_evaluation.replay.stage3.provider_calls_made() is False
        assert t2_evaluation.replay.stage3.cache_hits() == T2_SAMPLE

    def test_a_provider_that_raises_on_contact_is_never_contacted(
        self, benchmark_dir, corpus, tmp_path
    ):
        """Belt and braces: replay with a chain whose only provider explodes.

        The evaluator passes ``chain=None``, so this exercises the layer it
        stands on -- if replay ever reached for a provider, this raises.
        """
        from finrecon.agent.providers.chain import ProviderChain
        from finrecon.pipeline import process_batch
        from tests.stage3_fakes import ExplodingProvider

        with LedgerStore(":memory:") as store:
            batch = process_batch(store=store, benchmark_dir=benchmark_dir, split="dev")
            result = run_stage3(
                store=store,
                batch_result=batch,
                chain=ProviderChain((ExplodingProvider(),)),
                cache=TrajectoryCache(corpus["dir"]),
                replay_only=True,
                provider_id=FAKE_PROVIDER,
                model=FAKE_MODEL,
                case_ids=frozenset(corpus["t2"]),
                write_cache=False,
            )
        assert result.cache_hits() == len(corpus["t2"])
        assert not result.provider_calls_made()

    def test_a_missing_trajectory_fails_closed(self, benchmark_dir, corpus, tmp_path):
        config = _config(
            benchmark_dir,
            corpus,
            tmp_path,
            cohort_ids=(*corpus["t2"], "case:bnk_dev_000999"),
        )
        with pytest.raises(CohortError):
            evaluate(config, staging_dir=tmp_path / "stage")

    def test_an_empty_source_list_fails_rather_than_scoring_nothing(
        self, benchmark_dir, tmp_path
    ):
        config = EvaluationConfig(benchmark_dir=benchmark_dir, split="dev")
        with pytest.raises(EvaluationInputError, match="no trajectory source"):
            evaluate(config, staging_dir=tmp_path / "stage")

    def test_a_wrong_cache_identity_is_a_drift_error_not_a_live_run(
        self, benchmark_dir, corpus, tmp_path
    ):
        """Naming another model must never silently re-run the case."""
        config = _config(
            benchmark_dir,
            corpus,
            tmp_path,
            cohort_ids=corpus["t2"],
            model="some-other-model",
        )
        with pytest.raises(ReplayIntegrityError, match="cache key"):
            evaluate(config, staging_dir=tmp_path / "stage")

    def test_the_repository_fixture_directory_is_never_written_to(
        self, benchmark_dir, corpus, tmp_path
    ):
        from finrecon.agent.cache import DEFAULT_FIXTURE_DIR

        before = sorted(Path(DEFAULT_FIXTURE_DIR).glob("*.json"))
        config = _config(benchmark_dir, corpus, tmp_path, cohort_ids=corpus["t2"])
        evaluate(config, staging_dir=tmp_path / "stage")
        assert sorted(Path(DEFAULT_FIXTURE_DIR).glob("*.json")) == before


# --- production boundary ---------------------------------------------------


class TestProductionBoundaryIsIntact:
    def test_no_production_module_imports_the_evaluator(self):
        """The dependency arrow points one way: eval -> finrecon, never back."""
        import finrecon

        root = Path(finrecon.__file__).resolve().parent
        for path in sorted(root.rglob("*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                module = None
                if isinstance(node, ast.ImportFrom):
                    module = node.module or ""
                elif isinstance(node, ast.Import):
                    module = node.names[0].name
                if module and module.split(".")[0] == "benchmark" and "eval" in module:
                    pytest.fail(f"{path.name} imports the evaluator: {module}")

    def test_the_evaluator_lives_outside_the_installed_package(self):
        import finrecon

        import benchmark.eval as package

        finrecon_root = Path(finrecon.__file__).resolve().parent
        eval_root = Path(package.__file__).resolve().parent
        assert finrecon_root not in eval_root.parents
        assert "src" not in eval_root.parts

    def test_frozen_eval_truth_is_gated_behind_an_explicit_opt_in(self, benchmark_dir):
        with pytest.raises(GroundTruthPolicyError, match="gated"):
            load_ground_truth(benchmark_dir, "frozen-eval")
        allowed = load_ground_truth(
            benchmark_dir, "frozen-eval", allow_frozen_truth=True
        )
        assert len(allowed) == 890

    def test_dev_truth_needs_no_opt_in(self, benchmark_dir):
        assert len(load_ground_truth(benchmark_dir, "dev")) == 890

    def test_an_undeclared_split_is_refused(self, benchmark_dir):
        with pytest.raises(GroundTruthPolicyError, match="no ground-truth policy"):
            load_ground_truth(benchmark_dir, "nonexistent-split")


# --- sources ---------------------------------------------------------------


class TestSources:
    def test_utf16_dumps_are_decoded_by_bom_not_by_guessing(self):
        """UTF-16LE is valid UTF-8 byte-wise, so a naive ladder would corrupt it."""
        text = "case_id: xyz\n"
        assert decode_text(text.encode("utf-16")) == text
        assert decode_text(text.encode("utf-8")) == text
        assert decode_text(b"\xef\xbb\xbf" + text.encode("utf-8")) == text

    def test_a_run_dump_yields_its_trajectories(self, corpus, tmp_path):
        records = load_cache_dir(corpus["dir"])
        dump = tmp_path / "run.txt"
        body = ["summary header that is not JSON", ""]
        for record in records[:4]:
            body.append("=" * 72)
            body.append(json.dumps(record.payload, indent=2))
        dump.write_text("\n".join(body), encoding="utf-8")

        parsed = load_run_dump(dump)
        assert [r.case_id for r in parsed] == [r.case_id for r in records[:4]]
        assert all(r.source.startswith("dump:") for r in parsed)

    def test_a_dump_with_no_trajectories_fails_loudly(self, tmp_path):
        dump = tmp_path / "empty.txt"
        dump.write_text("investigated: 50\nresolved: 32\n", encoding="utf-8")
        with pytest.raises(EvaluationInputError, match="no trajectory records"):
            load_run_dump(dump)

    def test_a_cohort_can_be_derived_from_a_baseline_dump(self, corpus, tmp_path):
        records = load_cache_dir(corpus["dir"])
        dump = tmp_path / "baseline.txt"
        chunks = ["=" * 72 + "\n" + json.dumps(r.payload) for r in records[:5]]
        dump.write_text("\n".join(chunks), encoding="utf-8")
        assert cohort_from_records(load_run_dump(dump)) == tuple(
            sorted(r.case_id for r in records[:5])
        )

    def test_a_cohort_file_accepts_json_and_plain_lines(self, tmp_path):
        ids = ["case:a", "case:b"]
        as_json = tmp_path / "c.json"
        as_json.write_text(json.dumps(ids), encoding="utf-8")
        as_lines = tmp_path / "c.txt"
        as_lines.write_text("# comment\ncase:a\ncase:b\n", encoding="utf-8")
        wrapped = tmp_path / "w.json"
        wrapped.write_text(json.dumps({"case_ids": ids}), encoding="utf-8")
        assert read_cohort_file(as_json) == ("case:a", "case:b")
        assert read_cohort_file(as_lines) == ("case:a", "case:b")
        assert read_cohort_file(wrapped) == ("case:a", "case:b")

    def test_a_missing_source_fails_closed(self, tmp_path):
        with pytest.raises(EvaluationInputError):
            load_cache_dir(tmp_path / "nope")
        with pytest.raises(EvaluationInputError):
            load_run_dump(tmp_path / "nope.txt")


# --- comparison ------------------------------------------------------------


class TestComparison:
    def test_identical_cohorts_produce_deltas(self, t2_evaluation):
        report = t2_evaluation.report
        result = compare(report, report, label_a="same", label_b="same")
        assert result["cohort_identity"]["identical_case_ids"] is True
        assert result["cohort_identity"]["identical_tier_composition"] is True
        assert result["cohort_identity"]["comparable"] is True
        assert result["side_by_side"]
        for row in result["side_by_side"]:
            assert row["delta"] in (0, 0.0, None)
        assert result["configuration"]["differing_dimensions"] == []

    def test_mismatched_cohorts_are_refused(self, t2_evaluation):
        a = t2_evaluation.report
        b = json.loads(json.dumps(a))
        b["cohort"]["case_ids"] = b["cohort"]["case_ids"][:-1]
        with pytest.raises(CohortError, match="same cases"):
            compare(a, b)

    def test_a_mismatch_can_be_reconciled_without_deltas(self, t2_evaluation):
        a = t2_evaluation.report
        b = json.loads(json.dumps(a))
        b["cohort"]["case_ids"] = b["cohort"]["case_ids"][:-1]
        result = compare(a, b, require_identical_cohort=False)
        assert result["cohort_identity"]["identical_case_ids"] is False
        assert result["side_by_side"] == []
        assert len(result["cohort_identity"]["only_in_a"]) == 1

    def test_differing_tier_composition_blocks_deltas(self, t2_evaluation):
        a = t2_evaluation.report
        b = json.loads(json.dumps(a))
        b["cohort"]["tier_counts"] = {"T3": T2_SAMPLE}
        result = compare(a, b)
        assert result["cohort_identity"]["identical_tier_composition"] is False
        assert result["cohort_identity"]["comparable"] is False
        assert result["side_by_side"] == []

    def test_multiple_changed_dimensions_refuse_causal_attribution(
        self, t2_evaluation
    ):
        a = t2_evaluation.report
        b = json.loads(json.dumps(a))
        # Deliberately values the corpus cannot already have: the fixture is
        # recorded under the *current* prompt and tool versions, so reusing
        # those would silently assert nothing.
        assert b["recorded_versions"]["prompt_version"] != ["investigator.v0"]
        b["recorded_versions"]["prompt_version"] = ["investigator.v0"]
        b["recorded_versions"]["tool_schema_version"] = ["tools.v0"]
        b["telemetry"]["models_requested"] = {"gorouter:claude-opus-5-thinking": 1}
        result = compare(a, b)
        assert result["attribution"]["causal_claim"] is None
        assert result["attribution"]["differing_dimension_count"] == 3
        assert "No outcome difference can be attributed" in (
            result["attribution"]["statement"]
        )
        assert result["configuration"]["single_factor"] is False

    def test_a_single_changed_dimension_is_labelled_but_still_not_asserted(
        self, t2_evaluation
    ):
        a = t2_evaluation.report
        b = json.loads(json.dumps(a))
        b["recorded_versions"]["tool_schema_version"] = ["tools.v0"]
        result = compare(a, b)
        assert result["configuration"]["differing_dimensions"] == [
            "tool_schema_version"
        ]
        assert result["configuration"]["single_factor"] is True
        # Even a clean single-factor difference is not asserted as causal here.
        assert result["attribution"]["causal_claim"] is None


# --- report ----------------------------------------------------------------


class TestReportStability:
    def test_two_identical_evaluations_produce_byte_identical_json(
        self, benchmark_dir, corpus, tmp_path
    ):
        config = _config(
            benchmark_dir, corpus, tmp_path, cohort_ids=corpus["t2"], expected_tier="T2"
        )
        first = evaluate(config, staging_dir=tmp_path / "a")
        second = evaluate(config, staging_dir=tmp_path / "b")
        assert json.dumps(first.report, sort_keys=True) == json.dumps(
            second.report, sort_keys=True
        )

    def test_the_report_carries_no_timestamp_or_absolute_path(self, t2_evaluation):
        serialized = json.dumps(t2_evaluation.report)
        for leak in ("C:\\\\", "/home/", "/tmp/", "timestamp", "generated_at"):
            assert leak not in serialized, leak

    def test_the_report_has_every_required_section(self, t2_evaluation):
        report = t2_evaluation.report
        for section in (
            "evaluator_version",
            "configuration",
            "offline_guarantee",
            "cohort",
            "recorded_versions",
            "metrics",
            "agent",
            "telemetry",
            "soundness",
            "wrong_resolutions",
            "per_case",
        ):
            assert section in report, section
        assert len(report["per_case"]) == T2_SAMPLE

    def test_per_case_rows_carry_the_audit_trail(self, t2_evaluation):
        for row in t2_evaluation.report["per_case"]:
            assert row["case_id"].startswith("case:")
            assert row["tier"] == "T2"
            assert "termination_reason" in row
            assert "blockers" in row

    def test_the_report_is_json_serialisable_without_coercion(self, t2_evaluation):
        json.dumps(t2_evaluation.report, sort_keys=True, allow_nan=False)
