import { ChevronRight, Filter, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { money, query, shortId } from "../api";
import { friendlyCaseLabel } from "../lib/caseFormatting";
import { useApi } from "../hooks";
import type { CaseListResponse } from "../types";
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "../components/ui";

export default function Queue() {
  const [params] = useSearchParams(); const batch = params.get("batch"); const navigate = useNavigate();
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [source, setSource] = useState(""); const [escalated, setEscalated] = useState(false);
  const path = useMemo(() => `/api/cases${query(batch, { search, status, source, escalated_only: escalated })}`, [batch, search, status, source, escalated]);
  const { data, error, loading, reload } = useApi<CaseListResponse>(path);
  return <div className="page queue-page">
    <PageHeader eyebrow="Operations queue" title="Reconciliation queue" description="Search, triage, and inspect every financial case without collapsing its evidence." />
    <Card className="filter-bar"><label className="search-control"><Search size={16} /><span className="sr-only">Search cases</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search case, bank ID, or narration" /></label><div className="filter-divider" /><Filter size={15} className="muted" /><label><span className="sr-only">Status</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="resolved">Resolved</option><option value="needs_review">Needs review</option></select></label><label><span className="sr-only">Resolution source</span><select value={source} onChange={(e) => setSource(e.target.value)}><option value="">All sources</option><option value="deterministic">Deterministic</option><option value="ai_assisted">AI-assisted</option><option value="human">Human resolved</option><option value="escalated">Needs review</option></select></label><label className="check-control"><input type="checkbox" checked={escalated} onChange={(e) => setEscalated(e.target.checked)} /> Escalated only</label></Card>
    {loading ? <LoadingState label="Loading reconciliation queue" /> : error ? <ErrorState error={error} retry={reload} /> : !data?.cases.length ? <EmptyState title="No cases match these filters">Clear a filter, search another identifier, or run a reconciliation batch.</EmptyState> : <Card className="table-card"><div className="table-meta"><span><strong>{data.total}</strong> cases</span><span><ShieldCheck size={14} /> Complete candidate snapshots retained</span></div><div className="table-scroll"><table><thead><tr><th>Case / bank record</th><th>Narration</th><th className="amount-cell">Amount</th><th>Outcome</th><th>Candidates</th><th>Evidence</th><th>Updated</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{data.cases.map((item) => <tr key={item.case_id} tabIndex={0} onClick={() => navigate(`/cases/${encodeURIComponent(item.case_id)}?batch=${encodeURIComponent(item.batch_id)}`)} onKeyDown={(e) => { if (e.key === "Enter") navigate(`/cases/${encodeURIComponent(item.case_id)}?batch=${encodeURIComponent(item.batch_id)}`); }}><td><strong className="case-label" title={item.case_id}>{friendlyCaseLabel(item.bank_record_id, item.case_id)}</strong><span title={item.bank_record_id}>{shortId(item.bank_record_id, 34)}</span></td><td className="narration-cell" title={item.narration ?? ""}>{item.narration ?? "Not retained"}</td><td className="amount-cell"><strong>{money(item.amount_paise)}</strong></td><td><StatusBadge source={item.resolution_source} /></td><td>{item.candidate_count === 0 && item.resolution_source === "deterministic" ? <span className="direct-match">Direct match</span> : <span className="count-box">{item.candidate_count}</span>}</td><td><span className="evidence-label">{item.evidence_state}</span></td><td>{item.last_updated ? new Date(item.last_updated).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : <span className="muted">Ledger record</span>}</td><td><ChevronRight size={16} className="muted" /></td></tr>)}</tbody></table></div></Card>}
  </div>;
}
