import { ArchiveRestore, ArrowRight, Check, FileJson, FileSpreadsheet, FlaskConical, KeyRound, Play, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api, ApiError } from "../api";
import type { RunResponse } from "../types";
import { Button, Card, PageHeader } from "../components/ui";

function FileField({ label, accept, file, onChange, icon }: { label: string; accept: string; file: File | null; onChange: (file: File | null) => void; icon: React.ReactNode }) {
  const ref = useRef<HTMLInputElement>(null);
  return <button type="button" className={`file-field ${file ? "has-file" : ""}`} onClick={() => ref.current?.click()}><input ref={ref} className="sr-only" type="file" accept={accept} onChange={(e) => onChange(e.target.files?.[0] ?? null)} /><span className="file-icon">{file ? <Check size={18} /> : icon}</span><span><strong>{label}</strong><small>{file ? `${file.name} · ${(file.size / 1024).toFixed(1)} KB` : "Choose a file"}</small></span><UploadCloud size={17} /></button>;
}

export default function Run() {
  const navigate = useNavigate(); const [razorpay, setRazorpay] = useState<File | null>(null); const [bank, setBank] = useState<File | null>(null); const [profile, setProfile] = useState<File | null>(null); const [mode, setMode] = useState<"replay" | "live">("replay"); const [batchId, setBatchId] = useState(""); const [running, setRunning] = useState(false); const [status, setStatus] = useState(""); const [error, setError] = useState<string | null>(null); const [liveUnavailable, setLiveUnavailable] = useState(false);
  const complete = (result: RunResponse) => navigate(`/?batch=${encodeURIComponent(result.batch_id)}`);
  const runDemo = async () => { setRunning(true); setError(null); setLiveUnavailable(false); setStatus("Loading demo fixtures and replay trajectories…"); try { const result = await api<RunResponse>("/api/reconciliation/demo", { method: "POST" }); complete(result); } catch (e) { setError(e instanceof ApiError ? e.message : "The demo batch failed."); } finally { setRunning(false); setStatus(""); } };
  const runUpload = async () => { if (!razorpay || !bank || !profile) return; setRunning(true); setError(null); setLiveUnavailable(false); setStatus(mode === "replay" ? "Running deterministic stages and replaying cached investigations…" : "Running deterministic stages; unresolved cases may contact configured providers…"); const body = new FormData(); body.set("razorpay_file", razorpay); body.set("bank_file", bank); body.set("bank_profile", profile); body.set("mode", mode); if (batchId.trim()) body.set("batch_id", batchId.trim()); try { complete(await api<RunResponse>("/api/reconciliation/run", { method: "POST", body })); } catch (e) { setLiveUnavailable(e instanceof ApiError && e.code === "live_provider_not_configured"); setError(e instanceof ApiError ? e.message : "The reconciliation run failed."); } finally { setRunning(false); setStatus(""); } };
  return <div className="page run-page"><PageHeader eyebrow="New batch" title="Run reconciliation" description="Submit source data to the existing deterministic and bounded-investigation pipeline. Provider secrets stay on the server." />
    <div className="run-layout"><div className="run-main"><Card><div className="section-heading"><div><span className="step-label">01</span><h2>Source files</h2><p>Files are parsed by their existing adapters. Invalid source records are audited separately.</p></div></div><div className="file-grid"><FileField label="Razorpay recon file" accept=".json,application/json" file={razorpay} onChange={setRazorpay} icon={<FileJson size={18} />} /><FileField label="Bank CSV" accept=".csv,text/csv" file={bank} onChange={setBank} icon={<FileSpreadsheet size={18} />} /><FileField label="Bank profile / config" accept=".json,application/json" file={profile} onChange={setProfile} icon={<FileJson size={18} />} /></div><label className="field-label">Batch ID <span>Optional; generated when blank</span><input value={batchId} onChange={(e) => setBatchId(e.target.value)} placeholder="batch:august-settlement-run" /></label></Card>
      <Card><div className="section-heading"><div><span className="step-label">02</span><h2>Execution mode</h2><p>Stage 2 is deterministic in either mode. The difference applies only to unresolved Stage 3 cases.</p></div></div><div className="mode-grid"><button className={mode === "replay" ? "selected" : ""} onClick={() => setMode("replay")}><ArchiveRestore size={20} /><div><strong>Replay / Cached</strong><span>No paid or provider calls. Missing trajectories fail closed.</span></div><span className="mode-radio" /></button><button className={mode === "live" ? "selected" : ""} onClick={() => setMode("live")}><KeyRound size={20} /><div><strong>Live</strong><span>Unresolved Stage 3 cases may use server-configured providers.</span></div><span className="mode-radio" /></button></div><div className="secret-note"><KeyRound size={15} /> Credentials are read only from the backend environment and never sent to this browser.</div></Card>
      {error && <div className="run-error" role="alert">{liveUnavailable ? <><strong>Live investigation requires provider credentials on the self-hosted server.</strong><p>FinRecon never accepts provider secrets through the browser. Configure one or more backend environment variables—`OPENROUTER_API_KEY`, `GROQ_API_KEY`, `GEMINI_API_KEY`, or `GOROUTER_API_KEY`—as documented in `.env.example`, then restart the server.</p></> : error}</div>}{status && <div className="run-progress" role="status"><span className="progress-track"><i /></span><strong>Reconciliation in progress</strong><small>{status}</small></div>}
      <Button className="run-submit" disabled={running || !razorpay || !bank || !profile} onClick={runUpload}><Play size={16} /> {running ? "Running…" : "Run reconciliation"}</Button></div>
      <aside><Card className="demo-card"><div className="demo-icon"><FlaskConical size={22} /></div><span className="eyebrow">Judge-ready path</span><h2>Load demo batch</h2><p>Runs real adapters, Stage 2, cached Stage 3 replay, validation, policy, and SQLite persistence.</p><ul><li><Check size={14} /> Deterministic resolution</li><li><Check size={14} /> AI-assisted replay resolution</li><li><Check size={14} /> True ambiguity and human review</li><li><Check size={14} /> Separate ingestion quarantine</li></ul><Button variant="secondary" disabled={running} onClick={runDemo}>Load demo batch <ArrowRight size={15} /></Button><small>Zero network/provider calls</small></Card></aside>
    </div>
  </div>;
}
